import type { Metadata } from "next";
import type { Viewport } from "next";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import { Noto_Sans_Thai } from 'next/font/google';


const notoSansThai = Noto_Sans_Thai({
  weight: '400',
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: "Board Game Cafe",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={notoSansThai.className}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
